---
# services: docker

# env:
#   - distro: ubuntu1604
#   - ANSIBLE_VERSION: latest
#   - ANSIBLE_VERSION: 2.6.5
#   - ANSIBLE_VERSION: 2.5.10
#   - ANSIBLE_VERSION: 2.4.6.0

# script:
#   # Download test shim.
#   - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
#   - chmod +x ${PWD}/tests/test.sh
# # - make travis

sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - pip install tox-travis

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOX_ENV=py27-ansible25
      dist: xenial
    - python: 2.7
      env: TOX_ENV=py27-ansible26
      dist: xenial
  #   - python: "3.8-dev"
  #     env: TOX_ENV=py38
  #     dist: xenial
  #     if: branch = master AND type = push
  # allow_failures:
  #   - python: "3.8-dev"
  #     env: TOXENV=py38
  #     dist: xenial

cache:
  directories:
    - $HOME/.cache/pip
# script: travis_wait 30 tox --develop
script: tox -e $TOX_ENV
