# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  sysctl1:
    :hostname: "sysctl1"
    :ip: "192.168.36.100"
    :ram: 512
    :cpu: 1
    :box: "debian/stretch64"

:groups:
  servers:
    - sysctl1
