# -*- coding: utf-8 -*-
# tasks for  ansible-role-sysctl
---
# The 'sysctl' Ansible module was used previously, however using a template and
# 'sysctl --system' command is faster and doesn't create accidental idempotency
# loops when kernel parameters are modified in other configuration files.
- name: debug
  debug:
      var: bossjones__sysctl__config_file

- name: Generate kernel parameters config file
  template:
    src: 'etc/sysctl.d/bossjones.conf.j2'
    dest: "{{ bossjones__sysctl__config_file }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: bossjones__sysctl__register_config

- name: Check sysctl command capabilities
  shell: sysctl --help | grep -E '^\s+\-\-system\s+' || true
  register: bossjones__sysctl__register_system
  when: bossjones__sysctl__register_config|changed
  check_mode: False

- name: Apply kernel parameters if they were modified
  command: '{{ "sysctl --system"
               if (bossjones__sysctl__register_system.stdout != "")
               else ("sysctl -e -p " + bossjones__sysctl__config_file) }}'
  when: bossjones__sysctl__register_config|changed
