---
- name: Converge
  hosts: all
  become: yes
  become_method: sudo
  environment:
    SHELL: /bin/bash
  roles:
    # - role: boss-ansible-role-core
    # - role: boss-ansible-role-fact
    # - role: boss-ansible-role-environment
    - role: boss-ansible-role-sysctl
      bossjones__user: root
      bossjones__group: root
      bossjones__sysctl__host_parameters:
        'net.ipv6.conf.all.disable_ipv6':
          value: 1
          comment: |
            Disable IPv6 on all interfaces.
          state: "present"
        'net.core.somaxconn':
          value: 16384
          comment: |
            Limit of socket listen() backlog, known in userspace as SOMAXCONN.
            Defaults to 128.  See also tcp_max_syn_backlog for additional tuning
            for TCP sockets.
          state: "present"
        'net.ipv4.conf.all.accept_source_route':
            value: 0
            comment: |
              Our hosts aren't routers, so we can lock them down a bit
            state: "present"
        'net.ipv4.conf.all.send_redirects':
            value: 0
            comment: |
              Our hosts aren't routers, so we can lock them down a bit
            state: "present"
        'net.ipv4.conf.all.secure_redirects':
            value: 0
            comment: |
              Our hosts aren't routers, so we can lock them down a bit
            state: "present"
        'net.ipv4.conf.default.accept_redirects':
            value: 0
            comment: |
              Our hosts aren't routers, so we can lock them down a bit
            state: "present"
        'net.ipv4.conf.default.send_redirects':
            value: 0
            comment: |
              Our hosts aren't routers, so we can lock them down a bit
            state: "present"
        'net.ipv4.conf.default.secure_redirects':
            value: 0
            comment: |
              Our hosts aren't routers, so we can lock them down a bit
            state: "present"
        'net.ipv4.ip_local_port_range':
            value: 1024 65535
            comment: |
              Expanded so we don't run out of ephemeral ports, which are used by containers in BRIDGE mode (the default) and all outgoing connections from containers and our proxy
            state: "present"
        'net.core.rmem_default':
            value: 1048576
            comment: |
              Buffers. We choose high throughput over low latency.
            state: "present"
        'net.core.wmem_default':
            value: 1048576
            comment: |
              Buffers. We choose high throughput over low latency.
            state: "present"
        'net.core.rmem_max':
            value: 10485760
            comment: |
              Buffers. We choose high throughput over low latency.
            state: "present"
        'net.core.wmem_max':
            value: 10485760
            comment: |
              Buffers. We choose high throughput over low latency.
            state: "present"
